### ISSUE TITLE
Should understand manage_18 error from melinda-api

### ISSUE THREAD

**Issue by ammsalme** [NatLibFi/melinda-api-legacy-client#7]
{code}
 { messages:
   [ { code: '25000',
       message: 'Input record exceeds 25000 bytes, checking and updating may take longer than usual.' } ],
  errors:
   [ { code: -1,
       message: 'melinda-api-client unable to parse: Waited 10 secs in manage_18 queue, but could not start loading. Try again.' } ],
  triggers: [],
  warnings: [] }
{code}

**Comment by natlibfi-arlehiko** [comment]
Development has stopped.
